### ISSUE TITLE
Error Running Pipeline

### ISSUE THREAD

**Issue by DylanTom** [theislab/scib-pipeline#17]
TLDR: Error running pipeline, `ModuleNotFoundError: No module named 'scIB'`

I tried running this pipeline (using the included test data) and followed the instructions in the `README`. When I get to the section, `Running the Pipeline` and run the command `snakemake --configfile configs/test_data.yaml  --cores 6` it crashes. Attached is the traceback. The command `snakemake --configfile configs/test_data.yaml  -n` runs with no issue. What I did notice was the package name is `scib` but all the scripts and files used `scIB`. 

Traceback
```
(scib-R) [user scib-pipeline]$ snakemake --configfile configs/test_data.yaml --cores 6
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 6
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	5	convert_RDS_h5ad
	1	embeddings
	14	embeddings_single
	2	integration_prepare
	7	integration_run_python
	5	integration_run_r
	1	metrics
	14	metrics_single
	50

[Sun Feb  6 13:30:57 2022]
Job 11:
        Preparing adata
        wildcards: hvg=full_feature,prep=RDS,scaling=unscaled,scenario=test_data
        parameters: batch 0  -r -l conda run -n scib-pipeline
        output: /local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.RDS



[Sun Feb  6 13:30:57 2022]
Job 2:
        Preparing adata
        wildcards: hvg=full_feature,prep=h5ad,scaling=unscaled,scenario=test_data
        parameters: batch 0    conda run -n scib-pipeline
        output: /local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.h5ad


ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'scripts/preprocessing/runPP.py', '-i', 'data/adata_norm.h5ad', '-o', '/local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.RDS', '-b', 'batch', '--hvgs', '0', '-r', '-l']' command failed.  (See above for error)
Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 5, in <module>
    import scIB
ModuleNotFoundError: No module named 'scIB'

[Sun Feb  6 13:31:19 2022]
Error in rule integration_prepare:
    jobid: 11
    output: /local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.RDS
    shell:

        conda run -n scib-pipeline python scripts/preprocessing/runPP.py -i data/adata_norm.h5ad         -o /local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.RDS -b batch         --hvgs 0  -r -l

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'scripts/preprocessing/runPP.py', '-i', 'data/adata_norm.h5ad', '-o', '/local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.h5ad', '-b', 'batch', '--hvgs', '0']' command failed.  (See above for error)
Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 5, in <module>
    import scIB
ModuleNotFoundError: No module named 'scIB'

[Sun Feb  6 13:31:19 2022]
Error in rule integration_prepare:
    jobid: 2
    output: /local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.h5ad
    shell:

        conda run -n scib-pipeline python scripts/preprocessing/runPP.py -i data/adata_norm.h5ad         -o /local/workdir/dt425/scib-pipeline/data/test_data/prepare/unscaled/full_feature/adata_pre.h5ad -b batch         --hvgs 0

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /local/workdir/dt425/scib-pipeline/.snakemake/log/2022-02-06T133057.142601.snakemake.log
```

**Comment by mumichae** [comment]
The pipeline should now be updated to use the new scib package. Will close this issue
