### ISSUE TITLE
error goes with test data 

### ISSUE THREAD

**Issue by littleju714** [theislab/scib-pipeline#38]
Hi! Thank you so much for explaining the dry try step. But it goes wrong when I apply this:

> snakemake --configfile configs/test_data-R4.0.yaml --cores 10

The metrics step breaks several times at different jobid like other issue, but the key error seems different with them. 

```Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 263, in <module>
    trajectory_=trajectory_
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/metrics.py", line 414, in metrics
    verbose=verbose,
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/kbet.py", line 152, in kBET
    k0=k0,
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/kbet.py", line 201, in kBET_single
    "batch.estimate <- kBET("
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/__init__.py", line 438, in __call__
    res = self.eval(p)
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 199, in __call__
    .__call__(*args, **kwargs))
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/robjects/functions.py", line 125, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/rinterface_lib/conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "/home/data/vip19/mambaforge/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/rpy2/rinterface.py", line 677, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
rpy2.rinterface_lib.embedded.RRuntimeError: Error in is(object, "list") : object 'object' not found


[Sun May 29 02:16:56 2022]
Error in rule metrics_single:
    jobid: 24
    output: /home/data/vip19/tools/snakemake/scib-pipeline/data/test_data_r4/metrics/unscaled/full_feature/scanvi_embed.csv
    shell:
        
        conda run -n scib-pipeline-R4.0 python scripts/metrics/metrics.py -u data/adata_norm.h5ad -i /home/data/vip19/tools/snakemake/scib-pipeline/data/test_data_r4/integration/unscaled/full_feature/scanvi.h5ad          -o /home/data/vip19/tools/snakemake/scib-pipeline/data/test_data_r4/metrics/unscaled/full_feature/scanvi_embed.csv -m scanvi          -b batch -l celltype --type embed          --hvgs 0 --organism mouse --assay expression -v
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

ERROR conda.cli.main_run:execute(41): `conda run python scripts/metrics/metrics.py -u data/adata_norm.h5ad -i /home/data/vip19/tools/snakemake/scib-pipeline/data/test_data_r4/integration/unscaled/full_feature/scvi.h5ad -o /home/data/vip19/tools/snakemake/scib-pipeline/data/test_data_r4/metrics/unscaled/full_feature/scvi_embed.csv -m scvi -b batch -l celltype --type embed --hvgs 0 --organism mouse --assay expression -v` failed. (See above for error)
```

**Comment by LuckyMD** [comment]
I assume this might have to do with the pre-compiled knn graph function we use. Possibly the pre-compiled version works on this machine, but not the last one.
