### ISSUE TITLE
conda - /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by stemangiola** [theislab/scib-pipeline#39]
Hello,

I reinstalled `scib` within my conda environment `scib-pipeline-R4`

If I enter my environment
 
```
conda activate scib-pipeline-R4
cd /home/users/allstaff/mangiola.s/PostDoc/covid19pbmc/thirdparty_software/scib-pipeline
 ```
 
And execute
 
```
conda run -n scib-pipeline-R4 python scripts/metrics/metrics.py -u data/pbmc_simplified.h5ad -i /stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/mangiola.s/PostDoc/covid19pbmc/thirdparty_software/scib-pipeline/data_pbmc/run_pbmc/integration/scaled/full_feature/scgen.h5ad          -o /stornext/Bioinf/data/bioinf-data/Papenfuss_lab/projects/mangiola.s/PostDoc/covid19pbmc/thirdparty_software/scib-pipeline/data_pbmc/run_pbmc/metrics/scaled/full_feature/scgen_full.csv -m scgen          -b batch -l celltype --type full          --hvgs 0 --organism human --assay expression -v
 ```
 
I get the below error. How can I make python 3.7 in this environment to find all GLIBCXX it needs? Thanks!

(my IT support says it's all about the conda environment and not something they can fix from outside).
 
```
Isolated labels F1...
Isolated labels ASW...
Graph connectivity...
kBET...
cLISI score...
using precomputed kNN graph
Convert nearest neighbor matrix and distances for LISI.
Compute knn on shortest paths
call /home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/knn_graph/knn_graph.o /tmp/lisi_5z873agj/graph_lisi_input.mtx /tmp/lisi_5z873agj/graph_lisi 90 1 50
LISI score estimation
 
/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/knn_graph/knn_graph.o: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/knn_graph/knn_graph.o)
/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/knn_graph/knn_graph.o: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/knn_graph/knn_graph.o)
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 263, in <module>
    trajectory_=trajectory_
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/metrics.py", line 433, in metrics
    verbose=verbose,
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/lisi.py", line 151, in clisi_graph
    verbose=verbose,
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/lisi.py", line 299, in lisi_graph_py
    n_neighbors=n_neighbors,
  File "/home/users/allstaff/mangiola.s/.conda/envs/scib-pipeline-R4/lib/python3.7/site-packages/scib/metrics/lisi.py", line 408, in compute_simpson_index_graph
    if os.stat(index_file).st_size == 0:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/lisi_5z873agj/graph_lisi_indices_0.txt'
```

**Comment by stemangiola** [comment]
Hello, I was wondering if you have any advice on this.

**Comment by stemangiola** [comment]
I was wondering if you had any advice

**Comment by mumichae** [comment]
Hi,
This error is likely related to the following [issue](https://github.com/theislab/scib/issues/308). Try to install scib from github manually into the environment. That way it should be compiled on your system and work.
