### ISSUE TITLE
Pipeline can not find data in adata.obs

### ISSUE THREAD

**Issue by ccruizm** [theislab/scib-pipeline#49]
Good day,

I have been trying to run the pipeline with my own data but have failed so far. I used the test file, and the pipeline works and runs with no issues. However, once I input my data I get the error below:
```
Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                       count    min threads    max threads
----------------------  -------  -------------  -------------
all                           1              1              1
convert_RDS_h5ad             18              1              1
embeddings                    1              1              1
embeddings_single            46              1              1
integration_prepare           8              1              1
integration_run_python       20              1              1
integration_run_r            18              1              1
metrics                       1              1              1
metrics_single               46              1              1
total                       159              1              1

Select jobs to execute...

[Tue Nov  8 11:03:58 2022]
Job 2:
        Preparing adata
        wildcards: hvg=hvg,prep=h5ad,scaling=unscaled,scenario=gb_test
        parameters: batch 2000    conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad


[Tue Nov  8 11:04:00 2022]
Job 36:
        Preparing adata
        wildcards: hvg=full_feature,prep=RDS,scaling=scaled,scenario=gb_test
        parameters: batch 0 -s -r -l conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.RDS

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.RDS


[Tue Nov  8 11:04:00 2022]
Job 4:
        Preparing adata
        wildcards: hvg=full_feature,prep=h5ad,scaling=unscaled,scenario=gb_test
        parameters: batch 0    conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/full_feature/adata_pre.h5ad

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/full_feature/adata_pre.h5ad


[Tue Nov  8 11:04:00 2022]
Job 6:
        Preparing adata
        wildcards: hvg=hvg,prep=h5ad,scaling=scaled,scenario=gb_test
        parameters: batch 2000 -s   conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/hvg/adata_pre.h5ad

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/hvg/adata_pre.h5ad


[Tue Nov  8 11:04:00 2022]
Job 33:
        Preparing adata
        wildcards: hvg=hvg,prep=RDS,scaling=scaled,scenario=gb_test
        parameters: batch 2000 -s -r -l conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/hvg/adata_pre.RDS

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/hvg/adata_pre.RDS


[Tue Nov  8 11:04:00 2022]
Job 8:
        Preparing adata
        wildcards: hvg=full_feature,prep=h5ad,scaling=scaled,scenario=gb_test
        parameters: batch 0 -s   conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.h5ad

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.h5ad


[Tue Nov  8 11:04:00 2022]
Job 30:
        Preparing adata
        wildcards: hvg=full_feature,prep=RDS,scaling=unscaled,scenario=gb_test
        parameters: batch 0  -r -l conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/full_feature/adata_pre.RDS

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/full_feature/adata_pre.RDS


[Tue Nov  8 11:04:00 2022]
Job 27:
        Preparing adata
        wildcards: hvg=hvg,prep=RDS,scaling=unscaled,scenario=gb_test
        parameters: batch 2000  -r -l conda run -n scib-pipeline-R4.0
        output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.RDS

Reason: Missing output files: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.RDS

Scaling data ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 47, in runPP
    adata = scib.preprocessing.scale_batch(adata, batch)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 368, in scale_batch
    utils.check_batch(batch, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.RDS -b batch --hvgs 0 -s -r -l` failed. (See above for error)
Computing HVGs ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 43, in runPP
    adataOut=True
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 497, in hvg_batch
    utils.check_batch(batch_key, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad -b batch --hvgs 2000` failed. (See above for error)
[Tue Nov  8 11:05:21 2022]
[Tue Nov  8 11:05:21 2022]
Error in rule integration_prepare:
    jobid: 2
    output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad
    shell:

        conda run -n scib-pipeline-R4.0 python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad         -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad -b batch         --hvgs 2000

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Error in rule integration_prepare:
    jobid: 36
    output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.RDS
    shell:

        conda run -n scib-pipeline-R4.0 python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad         -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.RDS -b batch         --hvgs 0 -s -r -l

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Computing HVGs ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 36, in runPP
    adataOut=False
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 497, in hvg_batch
    utils.check_batch(batch_key, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.RDS -b batch --hvgs 2000 -r -l` failed. (See above for error)
Computing HVGs ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 36, in runPP
    adataOut=False
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 497, in hvg_batch
    utils.check_batch(batch_key, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/hvg/adata_pre.RDS -b batch --hvgs 2000 -s -r -l` failed. (See above for error)
Scaling data ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 47, in runPP
    adata = scib.preprocessing.scale_batch(adata, batch)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 368, in scale_batch
    utils.check_batch(batch, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/full_feature/adata_pre.h5ad -b batch --hvgs 0 -s` failed. (See above for error)
Computing HVGs ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 43, in runPP
    adataOut=True
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 497, in hvg_batch
    utils.check_batch(batch_key, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/scaled/hvg/adata_pre.h5ad -b batch --hvgs 2000 -s` failed. (See above for error)
[Tue Nov  8 11:05:21 2022]
[Tue Nov  8 11:05:21 2022]
Error in rule integration_prepare:
    jobid: 27
    output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.RDS
    shell:

        conda run -n scib-pipeline-R4.0 python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad         -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.RDS -b batch         --hvgs 2000  -r -l

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I really do not understand why it does not find the batch key when it is in the object. My Anndata object is a downsampled version for testing, which I created using `sc.pp.subsample(adata, fraction=0.01, copy=True)`. I am sharing the object here in case you want to look, and perhaps we can find the problem (https://we.tl/t-Ohdw4qk7LL).

Btw, I ran this interactive mode. I have not been able to make it work via SLURM. It is weird because it seems to activate the conda env where snakemake s installed, but later it does not find scanpy. I am attaching the script and output I got. I would greatly appreciate it if you have a suggestion how I could submit the job! 

Thanks in advance for your help! Please let me know whether any additional information is needed. 
[Scripts.zip](https://github.com/theislab/scib-pipeline/files/9960364/Scripts.zip)

**Comment by LuckyMD** [comment]
Hey!
I would guess that your config file doesn't match the dataset setup. Could you share your config file?

**Comment by ccruizm** [comment]
Sure! forgot to include it. Here it is 
[test_data-R4.0..zip](https://github.com/theislab/scib-pipeline/files/9960732/test_data-R4.0.zip)

**Comment by LuckyMD** [comment]
I can't seem to see the issue from your data. Could you show the snakemake command you are using? Could it be that you are not specifying the right config file with the `--configfile` parameter?

**Comment by ccruizm** [comment]
I am quite puzzled. I have spend quite sometime trying to figure out where the problem could be. Initially I thought it was a problem with my Anndata object (which in the end tried to make it as close as possible as the test file) but still have not been able to make it work. 

I have used `snakemake --configfile configs/test_data-R4.0.yaml --cores 24` and also `snakemake --configfile configs/test_data-R4.0t.yaml --cores 24 --use-conda`. Both failed.

**Comment by LuckyMD** [comment]
Maybe you can directly run the command that's failing: 
```
conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad -b batch --hvgs 2000
```

**Comment by ccruizm** [comment]
I get the same error 
```
Computing HVGs ...

Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 43, in runPP
    adataOut=True
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 497, in hvg_batch
    utils.check_batch(batch_key, adata.obs)
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/utils.py", line 12, in check_batch
    raise ValueError(f"column {batch} is not in obs")
ValueError: column batch is not in obs

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/gbmap_subset.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/prepare/unscaled/hvg/adata_pre.h5ad -b batch --hvgs 2000` failed. (See above for error)
```
Do not get why it does not find it :(

**Comment by mumichae** [comment]
Could you maybe double-check that the bath column is in the object? I couldn't reproduce the error on the data that you shared here

```
% python scripts/preprocessing/runPP.py -i ~/Downloads/subset.h5ad -o adata_pre.h5ad -b batch --hvgs 2000                                                                         

Computing HVGs ...
Using 0 HVGs from full intersect set
Using 2 HVGs from n_batch-1 set
Using 10 HVGs from n_batch-2 set
Using 39 HVGs from n_batch-3 set
Using 60 HVGs from n_batch-4 set
Using 57 HVGs from n_batch-5 set
Using 79 HVGs from n_batch-6 set
Using 105 HVGs from n_batch-7 set
Using 113 HVGs from n_batch-8 set
Using 146 HVGs from n_batch-9 set
Using 171 HVGs from n_batch-10 set
Using 255 HVGs from n_batch-11 set
Using 406 HVGs from n_batch-12 set
Using 557 HVGs from n_batch-13 set
Using 2000 HVGs
Save as HDF5
```

**Comment by ccruizm** [comment]
I found the mistake! so sorry. I was reading an older version of the file that did not have that metadata name! my apologies!

Now I notice I am getting this error:
```
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 263, in <module>
    trajectory_=trajectory_
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/metrics.py", line 362, in metrics
    organism=organism,
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 83, in cell_cycle
    verbose=verbose,
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 175, in get_pcr_before_after
    raw_sub.X, covariate, pca_var=None, n_comps=n_comps, verbose=verbose
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/pcr.py", line 167, in pc_regression
    copy=True,
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scanpy/preprocessing/_pca.py", line 196, in pca
    'svd_solver: {svd_solver} can not be used with sparse input.\n'
ValueError: svd_solver: {svd_solver} can not be used with sparse input.
Use "arpack" (the default) or "lobpcg" instead.

ERROR conda.cli.main_run:execute(49): `conda run python scripts/metrics/metrics.py -u data/gbmap_subset.h5ad -i /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/integration/scaled/hvg/combat.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/metrics/scaled/hvg/combat_full.csv -m combat -b batch -l celltype --type full --hvgs 2000 --organism human --assay expression -v` failed. (See above for error)
[Tue Nov  8 15:09:00 2022]
Error in rule metrics_single:
    jobid: 72
    output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/metrics/scaled/hvg/combat_full.csv
    shell:

        conda run -n scib-pipeline-R4.0 python scripts/metrics/metrics.py -u data/gbmap_subset.h5ad -i /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/integration/scaled/hvg/combat.h5ad          -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/metrics/scaled/hvg/combat_full.csv -m combat          -b batch -l celltype --type full          --hvgs 2000 --organism human --assay expression -v

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I noticed the test file contains an array in adata.X instead of a spare matrix. I guess I need also to store my matrix as array to avoid this error? (`adata.X = adata.X.toarray()`)

In addition, could you advise me on how to submit a SLURM job with the pipeline, please? I have tried, but it does not read the lib installed in the conda envs. 

Thanks for the speedy reply, and apologies again for the rooky mistake
