### ISSUE TITLE
KeyError: 'connectivities'

### ISSUE THREAD

**Issue by nrclaudio** [theislab/scib-pipeline#5]
Hi,

After installing both environments I've been trying to run the pipeline with the test data as suggested. However one of the metrics rules breaks. 

```
Error in rule metrics_single:
    jobid: 19
    output: /scib-pipeline/test_data/metrics/unscaled/full_feature/bbknn_knn.csv
    shell:
        
        conda run -n scIB-python python scripts/metrics/metrics.py -u data/adata_norm.h5ad -i /scib-pipeline/test_data/integration/unscaled/full_feature/bbknn.h5ad          -o /scib-pipeline/test_data/metrics/unscaled/full_feature/bbknn_knn.csv -m bbknn          -b batch -l celltype --type knn          --hvgs 0 --organism mouse --assay expression -v
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

This is the error inside that rule:

```
Job 19: 
        Metrics hvg=full_feature,method=bbknn,o_type=knn,scaling=unscaled,scenario=test_data
        output: /scib-pipeline/test_data/metrics/unscaled/full_feature/bbknn_knn.csv
        

ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', 'scripts/metrics/metrics.py', '-u', 'data/adata_norm.h5ad', '-i', '/scib-pipeline/test_data/integration/unscaled/full_feature/bbknn.h5ad', '-o', '/scib-pipeline/test_data/metrics/unscaled/full_feature/bbknn_knn.csv', '-m', 'bbknn', '-b', 'batch', '-l', 'celltype', '--type', 'knn', '--hvgs', '0', '--organism', 'mouse', '--assay', 'expression', '-v']' command failed.  (See above for error)
Options
    type:       knn
    batch_key:  batch
    label_key:  celltype
    assay:      expression
    organism:   mouse
    n_hvgs:     None
    setup:      bbknn_knn
    optimised clustering results:       /scib-pipeline/test_data/metrics/unscaled/full_feature/bbknn_knn_nmi.txt
reading adata before integration
AnnData object with n_obs × n_vars = 2730 × 3451 
    obs: 'paul15_clusters', 'celltype', 'batch', 'n_counts'
    var: 'n_counts'
    uns: 'iroot'
    layers: 'counts'
reading adata after integration
AnnData object with n_obs × n_vars = 2730 × 3451 
    obs: 'paul15_clusters', 'celltype', 'batch', 'n_counts'
    var: 'n_counts'
    uns: 'iroot', 'neighbors', 'pca'
    obsm: 'X_pca'
    varm: 'PCs'
    layers: 'counts'
reduce integrated data:
    HVG selection:      None
    compute neighbourhood graph:        False
    precompute PCA:     False
computing metrics
type:   knn
    ASW:        False
    NMI:        True
    ARI:        True
    PCR:        False
    cell cycle: False
    iso lab F1: True
    iso lab ASW:        False
    HVGs:       False
    kBET:       True
    LISI:       True
    Trajectory: False
clustering...
optimised clustering against celltype
optimal cluster resolution: 1.4
optimal score: 0.4182767661269383
saved clustering NMI values to /scib-pipeline/test_data/metrics/unscaled/full_feature/bbknn_knn_nmi.txt
NMI...
ARI...
isolated labels...
Graph connectivity...

conda_envs/scIB-python/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 248, in <module>
    trajectory_=trajectory_
  File "conda_envs/scIB-python/lib/python3.7/site-packages/scIB/metrics.py", line 1926, in metrics
    graph_conn_score = graph_connectivity(adata_int, label_key=label_key)
  File "conda_envs/scIB-python/lib/python3.7/site-packages/scIB/metrics.py", line 1795, in graph_connectivity
    _,labs = connected_components(adata_post_sub.obsp['connectivities'], connection='strong')
  File "conda_envs/scIB-python/lib/python3.7/site-packages/anndata/_core/aligned_mapping.py", line 112, in __getitem__
    _subset(self.parent_mapping[key], self.subset_idx),
  File "conda_envs/scIB-python/lib/python3.7/site-packages/anndata/_core/aligned_mapping.py", line 147, in __getitem__
    return self._data[key]
KeyError: 'connectivities'
```

Any idea how to troubleshoot this?

**Comment by nrclaudio** [comment]
Just for completion, _some_ versions:

```
# packages in environment at /conda_envs/scIB-python:
#
# Name                    Version                   Build  Channel
anndata                   0.7.1                    py37_0    conda-forge
bbknn                     1.3.9            py37h8f50634_1    bioconda
h5py                      2.10.0          nompi_py37ha3df211_106    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
igraph                    0.8.3                h689f727_2    conda-forge
keras                     2.3.0                    pypi_0    pypi
louvain                   0.6.1            py37h3340039_3    conda-forge
mnnpy                     0.1.9.5                  pypi_0    pypi
numpy                     1.18.1           py37h8960a57_1    conda-forge
pandas                    1.2.4            py37h219a48f_0    conda-forge
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
rpy2                      3.1.0           py37r36hc1659b7_3    conda-forge
scanorama                 1.7                        py_0    bioconda
scanpy                    1.4.6                      py_0    bioconda
scgen                     1.1.5                    pypi_0    pypi
scib                      0.1.1                    pypi_0    pypi
scikit-learn              0.24.2           py37h18a542f_0    conda-forge
scikit-misc               0.1.4                    pypi_0    pypi
scipy                     1.6.3            py37h29e03ee_0    conda-forge
scvi                      0.6.7                      py_0    bioconda
seaborn                   0.11.1               hd8ed1ab_1    conda-forge
statsmodels               0.12.2           py37h902c9e0_0    conda-forge
tensorflow                1.15.0          mkl_py37h28c19af_0  
torch                     1.8.1                    pypi_0    pypi
umap-learn                0.3.10                   py37_1    conda-forge
```

**Comment by LuckyMD** [comment]
This looks like an issue that is caught between an older scanpy version (that we initially used) and code that was adapted to work with an updated scanpy. Basically, from `scanpy 1.5.0` the connectivities are stored in `adata.obsp['connectivities']`. We adapted the `scIB` code to use this slot a couple of months ago. You are using `scanpy==1.4.6` which doesn't store the connecitivities in this slot yet, but instead in `adata.uns['neighbors']['connectivities']`. I would suggest updating to a newer scanpy version.

You can check whether my assumption is correct by loading the bbknn output you generated and checking what's stored in `adata.uns` and if you have `adata.obsp` or not.

**Comment by nrclaudio** [comment]
bbknn.h5ad keeps giving the same error after updating to `scanpy 1.5.0`. I suspect of `anndata 0.7.1`, I believe the transition to `obsp` was introduced in `0.7.2.` Will come back later today to report if updating `anndata` solves the issue.

**Comment by LuckyMD** [comment]
I'm assuming updating worked then @nrclaudio ?

**Comment by nrclaudio** [comment]
> I'm assuming updating worked then @nrclaudio ?

Yes, updating to `anndata 0.7.7` worked.

**Comment by LuckyMD** [comment]
thanks for adding the solution here :)
