### ISSUE TITLE
Error using sparse matrix

### ISSUE THREAD

**Issue by mumichae** [theislab/scib-pipeline#50]
Now I notice I am getting this error:
```
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 263, in <module>
    trajectory_=trajectory_
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/metrics.py", line 362, in metrics
    organism=organism,
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 83, in cell_cycle
    verbose=verbose,
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/cell_cycle.py", line 175, in get_pcr_before_after
    raw_sub.X, covariate, pca_var=None, n_comps=n_comps, verbose=verbose
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/pcr.py", line 167, in pc_regression
    copy=True,
  File "/home/cruiz2/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scanpy/preprocessing/_pca.py", line 196, in pca
    'svd_solver: {svd_solver} can not be used with sparse input.\n'
ValueError: svd_solver: {svd_solver} can not be used with sparse input.
Use "arpack" (the default) or "lobpcg" instead.

ERROR conda.cli.main_run:execute(49): `conda run python scripts/metrics/metrics.py -u data/gbmap_subset.h5ad -i /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/integration/scaled/hvg/combat.h5ad -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/metrics/scaled/hvg/combat_full.csv -m combat -b batch -l celltype --type full --hvgs 2000 --organism human --assay expression -v` failed. (See above for error)
[Tue Nov  8 15:09:00 2022]
Error in rule metrics_single:
    jobid: 72
    output: /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/metrics/scaled/hvg/combat_full.csv
    shell:

        conda run -n scib-pipeline-R4.0 python scripts/metrics/metrics.py -u data/gbmap_subset.h5ad -i /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/integration/scaled/hvg/combat.h5ad          -o /gpfs/work2/0/einf2548/cruiz/gbm/scib-pipeline/data/gb_test/metrics/scaled/hvg/combat_full.csv -m combat          -b batch -l celltype --type full          --hvgs 2000 --organism human --assay expression -v

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)
```

I noticed the test file contains an array in adata.X instead of a spare matrix. I guess I need also to store my matrix as array to avoid this error? (`adata.X = adata.X.toarray()`)

_Originally posted by @ccruizm in https://github.com/theislab/scib-pipeline/issues/49#issuecomment-1307293309_

**Comment by mumichae** [comment]
Yes, it seems some of the metrics were only developed on dense matrices. I'd need to update that in `scib`
