### ISSUE TITLE
Error in rule metrics_single.

### ISSUE THREAD

**Issue by zhongzheng1999** [theislab/scib-pipeline#61]
Hi !
Is this pipeline still being maintained?
I encountered an error while running the sample data.
A more specific error message is:
```
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 263, in <module>
    trajectory_=trajectory_
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/metrics.py", line 414, in metrics
    verbose=verbose,
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/kbet.py", line 150, in kBET
    k0=k0,
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/metrics/kbet.py", line 215, in kBET_single
    import anndata2ri
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/__init__.py", line 20, in <module>
    from . import _py2r, _r2py  # noqa: F401
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_py2r.py", line 14, in <module>
    from ._conv import converter, full_converter, mat_py2rpy
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_conv.py", line 10, in <module>
    from . import scipy2ri
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/scipy2ri/__init__.py", line 27, in <module>
    from . import _py2r, _r2py  # noqa: F401
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/scipy2ri/_py2r.py", line 18, in <module>
    from anndata2ri._rpy2_ext import importr
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_rpy2_ext.py", line 8, in <module>
    @lru_cache
  File "/home/u2204084007/.conda/envs/scib-pipeline-R4.0/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

ERROR conda.cli.main_run:execute(47): `conda run python scripts/metrics/metrics.py -u data/adata_norm.h5ad -i /home/u2204084007/biosoft/scib-pipeline-main/data/scib-R4.0_small/test_data_r4_small/integration/unscaled/full_feature/bbknn.h5ad -o /home/u2204084007/biosoft/scib-pipeline-main/data/scib-R4.0_small/test_data_r4_small/metrics/unscaled/full_feature/bbknn_knn.csv -m bbknn -b batch -l celltype --type knn --hvgs 0 --organism mouse --assay expression -v` failed. (See above for error)

Error in rule metrics_single:
    jobid: 8
    input: data/adata_norm.h5ad, /home/u2204084007/biosoft/scib-pipeline-main/data/scib-R4.0_small/test_data_r4_small/integration/unscaled/full_feature/bbknn.h5ad
    output: /home/u2204084007/biosoft/scib-pipeline-main/data/scib-R4.0_small/test_data_r4_small/metrics/unscaled/full_feature/bbknn_knn.csv
    shell:
        
        conda run -n scib-pipeline-R4.0 python scripts/metrics/metrics.py -u data/adata_norm.h5ad -i /home/u2204084007/biosoft/scib-pipeline-main/data/scib-R4.0_small/test_data_r4_small/integration/unscaled/full_feature/bbknn.h5ad          -o /home/u2204084007/biosoft/scib-pipeline-main/data/scib-R4.0_small/test_data_r4_small/metrics/unscaled/full_feature/bbknn_knn.csv -m bbknn          -b batch -l celltype --type knn          --hvgs 0 --organism mouse --assay expression -v
        
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!) 
```

Attached are my error log and configuration file
[2023-08-04T115620.309217.snakemake.log](https://github.com/theislab/scib-pipeline/files/12256971/2023-08-04T115620.309217.snakemake.log)
[test_data-R4.0_small.txt](https://github.com/theislab/scib-pipeline/files/12256977/test_data-R4.0_small.txt)

**Comment by zhongzheng1999** [comment]
I guess there are two reasons: 1. The python version is wrong? As others have mentioned, python3.7 cannot directly use `@lru_cache`, and python3.8 or higher is required[reference](https://stackoverflow.com/questions/47218313/use-functools-lru-cache-without-specifying-maxsize-parameter). 2, may be dependent on the version is wrong?[reference](https://github.com/GraiaProject/Application/issues/76)

Attached is a list of my conda environment packages.
[version.txt](https://github.com/theislab/scib-pipeline/files/12257219/version.txt)

**Comment by t-nol** [comment]
Same error (but different rule) while running the sample data.

```
        
Traceback (most recent call last):
  File "scripts/preprocessing/runPP.py", line 80, in <module>
    runPP(file, out, hvg, batch, rout, scale, seurat)
  File "scripts/preprocessing/runPP.py", line 51, in runPP
    scib.preprocessing.saveSeurat(adata, outPath, batch, hvgs)
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/_package_tools.py", line 21, in wrapper
    return func(*args, **kwargs)
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/scib/preprocessing.py", line 706, in save_seurat
    import anndata2ri
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/__init__.py", line 20, in <module>
    from . import _py2r, _r2py  # noqa: F401
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_py2r.py", line 14, in <module>
    from ._conv import converter, full_converter, mat_py2rpy
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_conv.py", line 10, in <module>
    from . import scipy2ri
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/scipy2ri/__init__.py", line 27, in <module>
    from . import _py2r, _r2py  # noqa: F401
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/scipy2ri/_py2r.py", line 18, in <module>
    from anndata2ri._rpy2_ext import importr
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_rpy2_ext.py", line 8, in <module>
    @lru_cache
  File "/CONDAS/users/tnoel/miniconda3/envs/scib-pipeline-R4.0/lib/python3.7/functools.py", line 490, in lru_cache
    raise TypeError('Expected maxsize to be an integer or None')
TypeError: Expected maxsize to be an integer or None

ERROR conda.cli.main_run:execute(49): `conda run python scripts/preprocessing/runPP.py -i data/adata_norm.h5ad -o /SCRATCH-BIRD/users/tnoel/scib-pipeline/data/test_data_r4/prepare/unscaled/full_feature/adata_pre.RDS -b batch --hvgs 0 -r -l` failed. (See above for error)
Save as RDS
```
Any news on this ?

**Comment by jesswhitts** [comment]
Also getting this error

I've tried to update the python version, but this just causes other conflicts...

**Comment by skim245** [comment]
@zhongzheng1999 i'm also have the same error. any updates?

**Comment by carlacohen** [comment]
I too am getting the same error as @zhongzheng1999 
I tried upgrading to python 3.8 but this caused other conflicts
Please let me know if anyone has a conda env for scib-pipeline-R4.0 that is currently working!

**Comment by Simon-chevolleau** [comment]
I'm also getting this error, I tried manually changing code of packages... bad idea, it did not succeed, anyway here is my attempt if anyone find it useful. Also, consider using containers instead of conda envs, it could avoid this problem.

`@lru_cache` syntax works for python=>3.8, instead use `@lru_cache()`, change this for:
- /home/simon/anaconda3/envs/mamba/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_rpy2_ext.py@13
- /home/simon/anaconda3/envs/mamba/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/scipy2ri/_py2r.py@33

Later, I had to change get_conversion definition by set_conversion:
/home/simon/anaconda3/envs/mamba/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/scipy2ri/_support.py@33
```py
from functools import lru_cache
from typing import TYPE_CHECKING
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal, get_args
```
/home/simon/anaconda3/envs/mamba/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/anndata2ri/_conv.py@22:
```py
    conversion.Converter('original anndata conversion', template=conversion.set_conversion())
```

Then:
- /home/simon/anaconda3/envs/mamba/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/optax/_src/base.py@17
- /home/simon/anaconda3/envs/mamba/envs/scib-pipeline-R4.0/lib/python3.7/site-packages/optax/_src/experimental/extra_args.py@27:
```python
from typing import Any, Callable, NamedTuple, Optional, Sequence, Tuple
from typing_extensions import Protocol
```

**Comment by mbuttner** [comment]
@zhongzheng1999 

If this is still relevant: I assume that the error message arises from a type issue handling with the kBET metric. As a quick fix, you could simply disable to compute kBET.

**Comment by kotr98** [comment]
I am facing the same problem. I disabled the computation of kBET and the test_data-R4.0_small.yaml ran through. 
However, when trying with test_data-R4.0.yaml, I get the same error as @t-nol.

Does anyone have a working environment to run the pipeline with most of the methods or is it a better approach to use the scib package to integrate with different methods and benchmark the metrics?

**Comment by zhongzheng1999** [comment]
The conflict seems to be mainly caused by scib updates. Because the latest version of scib requires pandas>2 and igraph>0.10 to conflict with the pipeline. It may work if the scib version is reduced. It seems to take some work to revive the pipe. I don't see any point in expending energy on it.
