### ISSUE TITLE
Suspected issue with scanpy version

### ISSUE THREAD

**Issue by wkopp** [theislab/scib-pipeline#7]
Hi @LuckyMD ,

I ran into an issue using the snakemake pipeline which I suspect might be due to a bug in scanpy.

I tried to run the pipeline on the test dataset using `snakemake --configfile configs/test_data.yaml`.
Running the rule `metrics_single` failed with

```
Trying to set attribute `.obs` of view, copying.
Trying to set attribute `.obs` of view, copying.
Trying to set attribute `.obs` of view, copying.
Trying to set attribute `.obs` of view, copying.
Trying to set attribute `.obs` of view, copying.
Traceback (most recent call last):
  File "scripts/metrics/metrics.py", line 248, in <module>
    trajectory_=trajectory_
  File "/home/wkopp/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scIB/metrics.py", line 1926, in metrics
    graph_conn_score = graph_connectivity(adata_int, label_key=label_key)
  File "/home/wkopp/anaconda3/envs/scIB-python/lib/python3.7/site-packages/scIB/metrics.py", line 1795, in graph_connectivity
    _,labs = connected_components(adata_post_sub.obsp['connectivities'], connection='strong')
  File "/home/wkopp/anaconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/aligned_mapping.py", line 112, in __getitem__
    _subset(self.parent_mapping[key], self.subset_idx),
  File "/home/wkopp/anaconda3/envs/scIB-python/lib/python3.7/site-packages/anndata/_core/aligned_mapping.py", line 147, in __getitem__
    return self._data[key]
KeyError: 'connectivities'
```

Suggesting that something failed when creating the neighborhood graph.

Then I did

```
import scanpy as sc
adata = sc.read_h5ad("data/adata_norm.h5ad")
sc.pp.pca(adata)
sc.pp.neighbors(adata)
adata
```
Which results in the following AnnData object:
```
AnnData object with n_obs × n_vars = 2730 × 3451 
    obs: 'paul15_clusters', 'celltype', 'batch', 'n_counts'
    var: 'n_counts'
    uns: 'iroot', 'pca', 'neighbors'
    obsm: 'X_pca'
    varm: 'PCs'
    layers: 'counts'
```
The 'connectivities' are missing here with scanpy==1.4.6.

I tried to do the same with scanpy==1.7.2 in which case I get the correct AnnData object:
```
>>> adata
AnnData object with n_obs × n_vars = 2730 × 3451
    obs: 'paul15_clusters', 'celltype', 'batch', 'n_counts'
    var: 'n_counts'
    uns: 'iroot', 'pca', 'neighbors'
    obsm: 'X_pca'
    varm: 'PCs'
    layers: 'counts'
    obsp: 'distances', 'connectivities'
```

Can you reproduce this issue?
Best,
Wolfgang

**Comment by LuckyMD** [comment]
Hi Wolfgang,

Thanks for pointing this out. It is already noted in issue [242](https://github.com/theislab/scib/issues/242) on the scIB github. I should be bumping scanpy requirements to >=1.5 and anndata to >=0.7.2

**Comment by LuckyMD** [comment]
Updated now via
https://github.com/theislab/scib/pull/243
